### ISSUE TITLE
Files Missing

### ISSUE THREAD

**Issue by KevinPatel04** [Nikhilkohli1/Real-Time-Interaction-Using-Sign-Language#1]
Hey @Nikhilkohli1,

I am trying to reproduce this code and re-train the model but few files are missing like `LSA_64.csv` mentioned in `LSA_64_Dataset_Dir_Structure_1.ipynb` due to which I am stuck. I have already downloaded  the LSA64 dataset using link provided in README.md.

Can you tell how to tackle this problem and guide me to reproduce this code onto my machine

Thanking You,

**Comment by KevinPatel04** [comment]
I have created it manually.

**Comment by Nikhilkohli1** [comment]
Hi Kevin, 

Thanks for letting me know. Its been a while I have touched this project, so there might be a few files which are not present in the repository. 

Some of the Example Data files which I had created are in the below repo as well - 

https://github.com/Nikhilkohli1/Dataset_Colored


Thanks, 
Nikhil

**Comment by KevinPatel04** [comment]
Hi Nikhil,

Can you provide pre-trained model weights file access? I have sent the request but still not accessible. 

And do you have all  LSA 64 dataset you used for training that model in google drive and can you share that link?  it might be helpful for me to run on Colab platform.
